#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Anver.Resource", IsApplication=true)]

namespace Anver
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F010001
			public const int button1 = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int debug = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int editText1 = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int editText2 = 2130771972;
			
			// aapt resource value: 0x7F010000
			public const int LoginBtn = 2130771968;
			
			// aapt resource value: 0x7F010005
			public const int pwText = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int relativeLayout1 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int scrollView1 = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int textView1 = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int textView2 = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int userText = 2130771978;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int Login = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Main = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
